add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[character]
success_symbol = '[λ](green)'
error_symbol = '[λ](red)'

[docker_context]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#fabfb4"
flamingo = "#ffa1a1"
pink = "#ff70d2"
mauve = "#cc1fc9"
red = "#ff638f"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#76ef39"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#8c9af5"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

